openapi: 3.0.0
info:
  title: Notifications API
  version: 0.0.1

paths:
  /notifications:
    get:
      summary: List user notifications
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 50
          description: Number of notifications to return (default 5)
        - name: cursor
          in: query
          schema:
            type: string
          description: Pagination cursor
        - name: onlyUnread
          in: query
          schema:
            type: boolean
          description: Return only unread notifications
      responses:
        "200":
          description: Notifications list
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Notification"
                  nextCursor:
                    type: string
                    nullable: true
        "401":
          description: Unauthorized

  /notifications/{notificationId}/read:
    post:
      summary: Mark a notification as read
      security:
        - bearerAuth: []
      parameters:
        - name: notificationId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Marked as read
        "401":
          description: Unauthorized
        "404":
          description: Notification not found

  /notifications/read-all:
    post:
      summary: Mark all notifications as read
      security:
        - bearerAuth: []
      responses:
        "204":
          description: All marked as read
        "401":
          description: Unauthorized

  /ws/notifications:
    get:
      summary: Real-time notifications via WebSocket
      description: >
        Opens a WebSocket connection that streams notification events 
        in real time.

        **Message Format:**
        All server-sent messages follow the `RealTimeNotification` schema.
      security:
        - bearerAuth: []
      responses:
        "101":
          description: Switching protocols
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RealTimeNotification"
              x-streaming: true
        "401":
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    NotificationType:
      type: string
      enum:
        - POST_LIKED
        - POST_COMMENTED
        - NEW_FOLLOWER

    UserSummary:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        avatar_url:
          type: string
          nullable: true
          format: uri

    Notification:
      type: object
      properties:
        id:
          type: string
        type:
          $ref: "#/components/schemas/NotificationType"
        created_at:
          type: string
          format: date-time
        is_read:
          type: boolean
        actor:
          $ref: "#/components/schemas/UserSummary"
        metadata:
          type: object
          description: Additional info depending on notification type
          properties:
            post_id:
              type: string
              nullable: true
            comment_id:
              type: string
              nullable: true

    RealTimeNotification:
      type: object
      description: Payload sent over WebSocket on notification events
      properties:
        event:
          $ref: "#/components/schemas/NotificationType"
        data:
          $ref: "#/components/schemas/Notification"
